import type { Metadata } from "next";
import { Text_Me_One, Poppins } from "next/font/google";
import "../globals.css";

const TextMeOne = Text_Me_One({
  variable: "--font-text-me-one",
  weight: "400",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MetamorphIA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (

<div className="relative flex min-h-dvh w-full flex-col overflow-hidden bg-[#F0F0F0]">
        <main className={`flex min-h-0 flex-1 ${poppins.variable} font-(family-name:--font-poppins) overflow-hidden`}>
          {children}
        </main>
      </div>
  );
}
